# Generated by Django 4.1.2 on 2023-03-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile_delete_usersignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
