# Generated by Django 4.1.2 on 2023-03-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
