# Generated by Django 4.1.2 on 2023-03-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_carousel_alter_userprofile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
